### ISSUE TITLE
a question about implementation

### ISSUE THREAD

**Issue by icoz69** [chalmersgit/EMD#2]
hello, thank you for your awesome implementation. 
i compare your work with opencv implementation and find a parameter cost .
https://docs.opencv.org/3.4.4/d6/dc7/group__imgproc__hist.html#ga902b8e60cc7075c8947345489221e0e0
but yours does not have such parameter.
i dont quite understand this. In my understanding, cost matrix is computed by the distance function, e.g. L2. why there are both cost matrix and distance function as the parameters?

**Comment by chalmersgit** [comment]
Hi, thanks for checking in.

I think you are correct. However I would imagine that the cost matrix is optional if you give it a known distance function from their API (e.g., DIST_L2). However, if you specify your own (DIST_USER) then you'd need to provide the cost matrix. Are you able to find success doing this?
